### ISSUE TITLE
Remove usage of jQuery from dependencies

### ISSUE THREAD

**Issue by jujyfruits** [ArkadiumInc/node-inhabit-module-base#14]
Now use $.extend method, to manage configuration. 
Can use www.npmjs.com/package/deep-extend package instead. The behavior is pretty the same as $.extend, except of overriting properties which was set to "undefined".

**Comment by rand0me** [comment]
Added [extend](https://npm.im/extend) cause it is a port of the classic extend() method from jQuery.
